use crate::constants::TILE_SIZE;

use super::{MAP_DISTANCE_IN_Z, MAP_END_Y, MAP_START_Y, PROPS_Z, WILL_BE_COMPUTE_LATER, Y_UNIT};

pub const SECRET_ROOM_EXIT_Y: f32 = MAP_END_Y;
pub const SECRET_ROOM_Z: f32 = (SECRET_ROOM_EXIT_Y - MAP_START_Y) * Y_UNIT - MAP_DISTANCE_IN_Z;

pub const SECRET_LOCATION_SENSOR_POSITION: (f32, f32, f32) = (-44.5, SECRET_ROOM_TRIGGER_Y, 0.);

pub const SECRET_ROOM_TRIGGER_Y: f32 = 85.5;
pub const SECRET_ROOM_TRIGGER_CUBOID: (f32, f32) = (7., 5.);
pub const SECRET_ROOM_TRIGGER_POSITION: (f32, f32, f32) = (-44.5, SECRET_ROOM_TRIGGER_Y, 0.);
pub const SECRET_ROOM_COVER_POSITION: (f32, f32, f32) = (-24., 161., 6.9);
pub const SECRET_ROOM_COVER_SIZE: (f32, f32) = (250., 100.);

pub const SECOND_FAKE_WALL_SWITCH_Z_OFFSET: f32 = -2.4;

pub const FAKE_STONE_POSITION: (f32, f32, f32) = (0., 0., WILL_BE_COMPUTE_LATER);
pub const FAKE_STONE_SWITCH_Z_OFFSET: f32 = -2.5;

pub const FLOWER_PANEL_SWITCH_Z_OFFSET: f32 = 0.3;
pub const FLOWER_PANEL_POSITIONS: [(f32, f32, f32); 5] = [
    (-116. * TILE_SIZE, 100.5 * TILE_SIZE, WILL_BE_COMPUTE_LATER), // 1
    (-83. * TILE_SIZE, 100.5 * TILE_SIZE, WILL_BE_COMPUTE_LATER),  // 2
    (35. * TILE_SIZE, 100.5 * TILE_SIZE, WILL_BE_COMPUTE_LATER),   // 3
    (68. * TILE_SIZE, 100.5 * TILE_SIZE, WILL_BE_COMPUTE_LATER),   // 4
    (-105.5 * TILE_SIZE, 165.5 * TILE_SIZE, WILL_BE_COMPUTE_LATER), // Repair
];

pub const WALL_POT_POSITION: (f32, f32, f32) = (-59.5 * TILE_SIZE, 171.5 * TILE_SIZE, PROPS_Z);

pub const STAIRS_RAMP_POSITION: (f32, f32, f32) =
    (-64.5 * TILE_SIZE, 141. * TILE_SIZE, WILL_BE_COMPUTE_LATER);
pub const STAIRS_RAMP_SWITCH_Z_OFFSET: f32 = -0.1;
