[package]
name = "fabien-et-la-trahison-de-olf"
version = "0.3.7"
authors = ["Morgan Van Amerongen <vanamerongen.morgan@gmail.com>", "Olf EPAIN <wabtey@disroot.org>", "Grassouille la Fripouille", "Sombre Roi René"]
edition = "2021"

[workspace]
resolver = "2"

[dependencies]
bevy = "0.8"
bevy_rapier2d = { version = "0.16", features = ["simd-stable", "debug-render"] }
bevy_tweening = "0.5" # { git = "https://github.com/djeedai/bevy_tweening", features = ["bevy_ui"], rev = "176f18e99673bbc0a2f249f2f7a7453aab2e1404" }
bevy-web-resizer = "3.0"
serde = "1.0"
ron = "0.7"
strum = "0.24"
strum_macros = "0.24"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
